### ISSUE TITLE
Cannot download videos

### ISSUE THREAD

**Issue by ghost** [keyurAdhyaru/Youtube-Downloader-#1]
Whenever I try to download a video with this, I get this error.
![pytube-error](https://user-images.githubusercontent.com/66498963/102097328-82316a80-3e04-11eb-8b57-2b275c5a1c3a.png)
I am unable to download videos, please help!

**Comment by mcg-git** [comment]
14 Dec 2020 since I opened this Issue LOL

**Comment by Pratyushkar** [comment]
Hey! I'm having the same error can you guide me about how to resolve this issue please?
